# Generated by Django 4.2.5 on 2024-08-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
