# Generated by Django 4.2.5 on 2024-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_songmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='song',
            field=models.TextField(null=True),
        ),
    ]
