# Generated by Django 4.2.5 on 2024-08-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_songmodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songmodel',
        ),
    ]
