# Generated by Django 4.2.5 on 2024-08-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_songmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistimage', models.ImageField(upload_to='images')),
                ('playlistname', models.TextField()),
                ('playlistartists', models.TextField()),
                ('number', models.TextField()),
                ('songimage', models.ImageField(upload_to='images')),
                ('songname', models.TextField()),
                ('songartist', models.TextField()),
                ('moviename', models.TextField()),
                ('plays', models.TextField()),
                ('duration', models.TextField()),
                ('song', models.TextField()),
            ],
        ),
    ]
