# Generated by Django 4.2.5 on 2024-08-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_categorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='songmodel',
            name='playlistartists',
        ),
        migrations.RemoveField(
            model_name='songmodel',
            name='playlistimage',
        ),
        migrations.RemoveField(
            model_name='songmodel',
            name='playlistname',
        ),
    ]
