# Generated by Django 4.2.5 on 2024-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_songmodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(null=True)),
                ('playlistimage', models.ImageField(upload_to='images')),
                ('playlistname', models.TextField()),
                ('playlistartists', models.TextField()),
            ],
        ),
    ]
