# Generated by Django 4.2.5 on 2024-08-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_subcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='palylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subcategorymodel'),
        ),
    ]
