# Generated by Django 5.1 on 2024-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_songmodel_palylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
