# Generated by Django 4.2.5 on 2024-08-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_subcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel'),
        ),
    ]
