# Generated by Django 4.2.5 on 2024-08-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_songmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='playlistname',
            field=models.TextField(null=True),
        ),
    ]
