# Generated by Django 4.2.5 on 2024-08-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_songmodel_playlistname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='categorylist',
            field=models.TextField(null=True),
        ),
    ]
