# Generated by Django 4.2.5 on 2024-08-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_subcategorymodel_categorylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='categorylist',
        ),
    ]
