# Generated by Django 4.2.5 on 2024-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_subcategorymodel_categorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='category_name',
            field=models.TextField(null=True),
        ),
    ]
