# Generated by Django 4.2.16 on 2024-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_songmodel_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
